# Last updated: 21-DEC-2025
baseURL = 'https://maroph.github.io/nosense/'
DefaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'No Sense'
timeZone = 'Europe/Berlin'
theme = 'beautifulhugo'
pygmentsStyle = 'trac'
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
enableGitInfo = false

[params]
  subtitle = 'Some of my stupid thoughts'
  selfHosted = true
  favicon = 'images/favicon_hugo-32x32.png'
  logo = 'images/great_wave_off_kanagawa_200x200.jpg'
  # since = 2025
  mainSections = ['posts']
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  hideAuthor = true
  [params.author]
    name = 'maroph'
    website = 'https://maroph.github.io/'
    github = 'maroph'
    mastodon = 'https://mastodon.social/@maroph'
    codepen = 'maroph'

[menus]
  [[menus.main]]
    name = 'Info'
    pageRef = 'pages/info'
  [[menus.main]]
    parent = 'Info'
    name = 'About'
    url = 'pages/info/about/'
  [[menus.main]]
    parent = 'Info'
    name = 'maroph.github.io'
    url = 'https://maroph.github.io/'
  # [[menus.main]]
  #   name = 'Notes'
  #   pageRef = 'pages/notes'
  # [[menus.main]]
  #   parent = 'Notes'
  #   name = 'Note'
  #   url = 'pages/notes/note/'
  #   weight = 1

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.x]
    disable = true
  [privacy.youTube]
    disable = true

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

